version: "3.5"

services:
  postgres:
    container_name: postgres
    image: arm32v7/postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      # copy the sql script to create tables
      # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql`
    logging:
      options:
        max-size: 10m
        max-file: "3"
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
